### PR TITLE
WIP: one to multiple source maps #21

### LINKED ISSUE #21: add support for 1:many source-maps
we should add support for source-maps that map from one transpiled source to many original sources, this is an extension to the work done in https://github.com/istanbuljs/v8-to-istanbul/pull/19.

### PR DESCRIPTION
**Pull request by DracoBlue**
I am trying to fix #21 and `v8-to-istanbul: source-mappings from one to many files not yet supported`

Approach:

0. v8-to-istanbul.js expects only one file of the sourcemap to be parsed at the same time
1. create a new method and walk through all source files of the sourcemap and reset state (this. sourceTranspiled and this.source) before

### CODE REVIEW

**Comment by bcoe** [comment]
👋 hey @DracoBlue, I apologize for not having had much time to look at this project lately. I'm excited that your'e looking into this.

**Comment by bcoe** [comment]
@DracoBlue still something you'd like to land, looks like a few tests are failing.

**Comment by DracoBlue** [comment]
@bcoe Yup. The test are failing because of the result dump. I am currently trying to get it working with a big webpack-based project. if this works properly I will add tests for my usecase and update the PR here.

**Comment by bcoe** [comment]
@DracoBlue very much appreciated :clap: we just landed some source-map related functionality in Node.js core, that's made me excited about dusting off these libraries ... they now work for edge-cases like `ts-node`.

**Comment by DracoBlue** [comment]
Nice!

I am currently struggling with those member variables. Hopefully I get this sorted within next days. Having v8 istanbul reporting for production sourcemap files would help me to end2end test our production build with little effort ;).

**Comment by SergeyPirogov** [comment]
@DracoBlue what is the progress with this? I struggling with the same issue.

**Comment by SergeyPirogov** [comment]
I've added these changes to my project and when trying to generate the report it's failing:
```
file: /home/sergey/Github/todomvc/examples/typescript-angular/js/Application.js error: TypeError: Cannot read property '0' of undefined
    at /home/sergey/Github/todomvc/examples/typescript-angular/node_modules/v8-to-istanbul/lib/v8-to-istanbul.js:66:75
    at async Promise.all (index 0)
    at async V8ToIstanbul.load (/home/sergey/Github/todomvc/examples/typescript-angular/node_modules/v8-to-istanbul/lib/v8-to-istanbul.js:46:39)
    at async Report.getCoverageMapFromAllCoverageFiles (/home/sergey/Github/todomvc/examples/typescript-angular/node_modules/c8/lib/report.js:69:9)
    at async Report.run (/home/sergey/Github/todomvc/examples/typescript-angular/node_modules/c8/lib/report.js:39:17)
    at async Object.exports.outputReport (/home/sergey/Github/todomvc/examples/typescript-angular/node_modules/c8/lib/commands/report.js:24:3)
    at async Object.exports.handler (/home/sergey/Github/todomvc/examples/typescript-angular/node_modules/c8/lib/commands/report.js:9:3)
```

**Comment by DracoBlue** [comment]
I am still struggling with the code, since some of these member variables are used elsewhere and it is not easy to emulate.

My ncc build does not highlight properly at all. So long I close this PR until I have time for this matter again.

**Comment by SergeyPirogov** [comment]
Will try to complete this

**Pull request closed without merging**
