### PR TITLE
fix: handle end out of range errors

### PR DESCRIPTION
**Pull request by hurstindustries**
Fixes issue `Cannot read properties of undefined (reading 'endCol')` in `lib/range.js`

See comment by @devcorraliza on  https://github.com/istanbuljs/v8-to-istanbul/issues/198#issuecomment-1310007608 for context

### CODE REVIEW

**Comment by SimenB** [comment]
Please include a test 🙂

**Comment by devcorraliza** [comment]
Hi, any pending task to review/merge?

**Comment by wolandec** [comment]
Hi, could you please release this change?

**Comment by SimenB** [comment]
@jridgewell does this seem reasonable to you?

**Review by jridgewell — CHANGES_REQUESTED** [review]
I think this fix is in the wrong location, because it's so far from the actual spot the bug is introduced. I would update https://github.com/istanbuljs/v8-to-istanbul/blob/b5ecd8242cf64389c9a656d78530bd0428edf195/lib/source.js#L105-L110

```js
      const maybeEnd = originalPositionFor(sourceMap, {
        line: lines[lines.length - 1].line,
        column: endCol - lines[lines.length - 1].startCol,
        bias: LEAST_UPPER_BOUND
      })
      if (maybeEnd) {
        end = maybeEnd
        end.column -= 1
      }

**Comment by bcoe** [comment]
Not sure what the best solution is here between the options presented by @jridgewell, @wolandec, and @hurstindustries -- open to suggestions from someone who's dug into this deeply.

**Pull request closed without merging**
