### PR TITLE
Retry end (fixes #170)

### LINKED ISSUE #170: Coverage false positive
I am working on this project https://github.com/glromeo/cypress-c8 to generate code coverage in cypress without using babel.
I have noticed that **a function that's the only export of a module is reported as covered when it shouldn't.**
I did a bit of debugging and the issue seems to be within v8-to-instanbul 

https://github.com/istanbuljs/v8-to-istanbul/blob/53c1cd89cb46f4cd2c0a23cdb31715de09716a2a/lib/v8-to-istanbul.js#L179

maybe for a sourcemap mismatch?

### PR DESCRIPTION
**Pull request by glromeo**
This PR aims at improving the `startCol`/`endCol` (source)mapping by finding the greatest lower bound when there's a start but an exact mapping for the end itself doesn't exist.
This append in particular when build tools (like `esbuild` o `rollup`) do not to map `}` so instead of it we pick the latest mapped statement.

There's one change in v8 tests snapshot and looking carefully at it this is the addition of a branch which was missed before (see selection):
image

A bit more interesting is what happens in `c8` where only 1 test fails:
```
  51 passing (21s)
  1 failing

      AssertionError: expected value to match snapshot c8 source-maps TypeScript remaps branches 1
      + expected - actual

       a = false
       ------------------------|---------|----------|---------|---------|-------------------
       File                    | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
       ------------------------|---------|----------|---------|---------|-------------------
      -All files               |      84 |    57.14 |     100 |      84 |
      - branches.typescript.ts |      84 |    57.14 |     100 |      84 | 7,11-12,18
      +All files               |      84 |       50 |     100 |      84 |
      + branches.typescript.ts |      84 |       50 |     100 |      84 | 7,11-12,18
       ------------------------|---------|----------|---------|---------|-------------------
```
Although looking at the source code it seems that there are 3+3=6 branches and 3 of them are never touched
hence 50% coverage when looking at what v8 blocks contain:
image
we can see that out of 7 ranges 3 are not covered.
And according to:
https://github.com/istanbuljs/v8-to-istanbul/blob/1f357fa2e994385b56ba505ca199eda46b233a89/lib/v8-to-istanbul.js#L154-L160
it seems that each range is a branch so the 4/7=57.14% should be correct.

@bcoe what do you think?

### CODE REVIEW

**Comment by glromeo** [comment]
@bcoe esbuild is emitting the mappings for `}` now but there might still be cases in which ranges are missed because a mapping is not present so I consider this PR still meaningful

**Comment by bcoe** [comment]
@glromeo where does this and #179 stand, with your other fixes that we've landed?

**Comment by glromeo** [comment]
@bcoe unfortunately this PR needs some work due to the latest changes

**Comment by bcoe** [comment]
@glromeo seems like we've lost steam on this PR, which is okay 😄  (I totally understand).

If we want to dust the work off eventually let me know.

**Pull request closed without merging**
