### PR TITLE
use the inline source content if avilable

### PR DESCRIPTION
**Pull request by Toxicable**
For context see here: https://github.com/bcoe/c8/issues/197

### CODE REVIEW

**Comment by bcoe** [comment]
@Toxicable so the concern here, is if someone is in an environment where they can't access the source off disk, the HTML reports will throw errors (not a problem for other reports?).

**Comment by Toxicable** [comment]
@bcoe Correct
So generally this means v8-to-istanbul won't "validate" the path back to the original source file.
For our specific use case that's fine since we'll work around it.
But for the general I think this is still a reasonable change since it'll reduce the amount of fs calls needed when using inline source maps.

**Comment by bcoe** [comment]
@Toxicable thanks for the contribution :+1: 

It seems like we could potentially get the HTML reports working with some additional work? perhaps it's worth opening a tracking ticket?

**Comment by Toxicable** [comment]
Ill do some more work to ensure this stage of the integration works well, then will swing back around to look at the HTML stuff again.
We may be able to solve those issues from the input/bazel side of things

**Pull request merged**
